# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Home Assistant' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Home Assistant
  pod 'JSQMessagesViewController'
  pod 'CocoaMQTT'
  pod 'SwiftyJSON'
  pod 'BluemixObjectStorage'

end
